title: Pattern Recognition and Machine Learning Vietsub
author: Lê Nguyễn 
simple_search: http://google.com/search
description: An attemption to create a reference for Vietnamese student when learning PRML
name: prml-vietsub
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Asia/Ho_Chi_Minh
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
